#
# makefile
#

all:
	(cd 7.6; make)
	(cd 7.7; make)
	(cd 7.9; make)
	(cd 7.13; make)

test:
	(cd 7.6; make test)
	(cd 7.7; make test)
	(cd 7.9; make test)
	(cd 7.13; make test)

.PHONY : clean
clean:
	(cd 7.6; make clean)
	(cd 7.7; make clean)
	(cd 7.9; make clean)
	(cd 7.13; make clean)

# vim:ft=make
#
